project_id = "gukzpbzqprlxtdxhopxl"

[functions.get-greeting]
verify_jwt = false

[functions.payflex-data-topup]
verify_jwt = false

[functions.payflex-airtime-topup]
verify_jwt = false

[functions.verify-nin]
verify_jwt = false

[functions.spending-analytics]
verify_jwt = false

[functions.secure-transaction-update]
verify_jwt = false

[functions.budget-management]
verify_jwt = false